### ISSUE TITLE
Portal mobile version

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#1228]
As any Portal user
I want to be able to open the portal website on the mobile devices  
So that I can consume the content in a convenient way

**Comment by pzhuk** [comment]
We would be glad to hear any best practices about it - since we don't have a large domain experience in the area. 
When speaking about mobile devices - we mean only smartphones, Android 4.4+ and iOS based.

Also, if this makes any sense - may be we should consider adaptation of the portal web content in a way, so it could be in the future integrated into some mobile app - I am not sure, but I suspect it's a very similar activity to the mobile website adaptation itself.

**Comment by pzhuk** [comment]
Also, definitely one of the main scopes for this task - is the adaptation of design for mobile deviece with a touchscheen, so user touch experience is provided in a best way.

**Comment by lymychp** [comment]
@pzhuk as a delivery of this task there will be mobile version with the responsive design of the existing portal. It will be adopted for the mobile devices, so user touch experience will be provided in the best way on smartphones or tablets. 
[design](https://www.dropbox.com/sh/os1es77b27yewu3/AADeFh14OMfdPd0g2qQ10KVfa?dl=0)

**Comment by lymychp** [comment]
implementation task #1241
