### ISSUE TITLE
Set up BI Tool for fraud 

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#1385]
There is a need to have BI connected to fraud db in order to be able to configure reports

- [x] BI Tool deployed and connected

**Comment by lymychp** [comment]
Short List
>Open Source Business Intelligence Solutions
>* **BIRT**
BIRT is an open source BI program that is “often seen as the industry standard.” This perception has a lot of truth to it, as BIRT boasts “over 12 million downloads and over 2.5M developers across 157 countries.” Their users include heavyweights such as Cisco, S1, and IBM (which is also a BIRT sponsor). They also have maturity going for them, as they’ve been around since the (second) Bush administration.
BIRT can create a range of reports, from textual documents to crosstabs to standard pie and bar graphs. Along with these BI basics, BIRT can also tackle slightly more advanced tasks, “such as grouping on sums, percentages of overall totals and more.” BIRT can also be embedded in a range of other applications, so it may integrate with business software you already use. BIRT is also great if you run an application that uses Java, as components such as BIRT’s report engine and charting engine integrate easily with applications and programs that use Java.
Be aware, however, that you’ll need someone who knows code to be able to really work the program. If you’re left scratching your head at terms like “conditional formatting” or “scripted data sets,” you may be in over your head.

>* **Jaspersoft Community**
You’ll run into Jaspersoft pretty quickly if you search for open source BI tools, but it may be awhile before you encounter this fact: Jaspersoft was bought up by Tibco in April of 2014. How good is Jaspersoft? Good enough that Tibco spent $185 million to acquire them.
Jaspersoft Community is the company’s free offering. Jaspersoft offers five of their programs in Community editions:
JasperReports Server: A program for designing reports that can be embedded, or used on its own
JasperReports Library: A Java library that allows you to use data from any source, and export reports in HTML, PDF, Excel, and other formats
Jaspersoft ETL: a data integration engine that transforms your business data into information that can be used in a report
Jaspersoft Studio: A program that lets you design and customize the reports you’ll embed in JasperReports Server
Visualize.JS: a Javascript framework that embeds Jaspersoft applications in whatever software you already use
Jaspersoft’s website states that 94% of customers recommend their product, and 90% recommend their support. Though that fact’s from their website, you can’t argue with their impressive list of customers: everyone from Groupon to Time Warner Cable to the government of British Columbia and Vanderbilt University.
Like a lot of open source programs, Jaspersoft has a developer community, an online forum for people who use and, well, develop that open source code into a fuller program.
The upside to developer communities for any open source program is that you’ve got a potential support network, or at least people with similar concerns. The downside is that, since developer communities are populated by users, rather than paid customer service advisors, you take your chances when you look for help.
For example, on the Jaspersoft Community Answers page, you can post questions to the community of developers, at large, on an online forum. Whether you get an answer depends on whether another developer has the time, or interest, to offer a solution. As this article’s writing, the odds weren’t bad: 11 of the 20 questions on the first page had answers.

>* **Pentaho Community Edition**
Pentaho was bought by Hitachi, and now makes up one part of Hitachi Ventara. They’re still called Pentaho, though.They offer a lot of helpful BI basics such as visualizations from heat graphs to geo-mapping, as well as reporting in outputs as diverse as PDFs, Excel, HTML, and others. They offer an Enterprise Edition (for which you’ll have to buy a subscription) and a Community Edition (free and open source). As with Jaspersoft, your business will need someone who knows how to code if you want to really take advantage.
If you do have coders on hand, Pentaho is a great choice. The customizability one gets from coding is strengthened by offerings such as Pentaho’s CTools, which are “tools and components created to help you build Custom Dashboards on top of Pentaho.” The tools allow you to perform an impressive range of activities, such as creating more advanced dashboards or incorporating extra graphics for reports.
Like Jaspersoft, Pentaho offers community forums that allow you to discuss developments or changes you’ve made to the code, or ask questions. The odds aren’t bad for getting an answer. The forums for data integration and CTools are a good place to find answers, but the Reporting section of the forums is the equivalent of digital crickets chirping.
Pentaho definitely tries to take the idea of a developer community seriously. There’s a list of real-life groups, with links to meetup.com, but a lot of the groups haven’t had meetings in months. The exception is Business Intelligence Big Data Integration ETL Analysts. They’re based out of NYC, but two of their last three meetings were free webinars, so geography’s hardly an issue.

>* **MS Power BI**

**Comment by vsirius** [comment]
Microsoft Power Bi deployed on google cloud  Microsoft Windows Server 2016    and connected to Fraud db.
