### ISSUE TITLE
Session Cookie Without Secure and HttpOnly Flags Set

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#1560]
Application does not set two mandatory security flags, Secure and HttpOnly, to the session
identifier in token cookie.
If the Secure flag is set on a cookie, then browsers will not submit the cookie in any requests that use an unencrypted HTTP connection, thereby preventing the cookie from being trivially intercepted by an attacker monitoring the network traffic.
If the HttpOnly attribute is set on a cookie, then the cookie's value cannot be read or set by client- side JavaScript. This measure makes certain client-side attacks, such as cross-site scripting, slightly harder to exploit by preventing them from trivially capturing the cookie's value via an injected script.
<img width="870" alt="screen shot 2017-11-29 at 4 46 18 pm" src="https://user-images.githubusercontent.com/5257001/33380792-e3b0106e-d524-11e7-9691-241d467a3bb2.png">

**Recommendations**
The Secure flag should be set on all cookies that are used for transmitting sensitive data when accessing content over HTTPS.
Set the HttpOnly flag on the session cookie to protect it from being captured via trivial XSS attacks.

**Comment by ynotLeft** [comment]
There should be no problems with 'secure' flag, but setting 'httpOnly' contradicts current implementation of communication between web and API.
Gateway expects authorization token in the header of requests and to do that we have to store token in cookies or other kind of persistent storage. Setting 'httpOnly' will unable us to read token and add it to headers. 
Using  session or local storage for storing authorization token instead of cookies will not fix the problem as that will open same XSS vulnerabilities that 'httpOnly' deals with for cookies. 
To solve security issue we can try to enable cookies reading on the gateway. This link can be useful. 
https://github.com/Kong/kong/issues/2894
