### ISSUE TITLE
Persons without declarations

### ISSUE THREAD

**Issue by danakonovalenko** [edenlabllc/ehealth.api#2068]
We have 58 MPIs without declarations which were inserted during 2 hours 5-7 pm 02.04.2018
```
select *
from persons p left join declarations dec on p.id=dec.person_id
where dec.id is null and p.inserted_at::date=date'2018-04-02'
```
We need to clarify why it happened.

**Comment by gmile** [comment]
A long-shot guess for now: there's a declaration creation process, of which mpi creation is a part of, that didn't finish successfully. Hence MPI was created, but declaration didn't.

@danakonovalenko what do you think?

**Comment by lymychp** [comment]
@gmile 
1. we should be sure
2. we should find proofs of this theory at least for few records
3. we should investigate what exactly went wrong with the declaration sign process. 

The main point that it has happened just BEFORE release

**Comment by gmile** [comment]
> The main point that it has happened just BEFORE release

I missed that! Good point.

**Comment by lymychp** [comment]
sign declaration request is a multi-step process with the orchestration of different services: ael, mpi, declarations, etc. There is no transaction within the orchestration. That's why the steps order that has been chosen suppose that we might have mpi without declaration, but there shouldn't be any declaration without mpi. And this is the case.
