### ISSUE TITLE
MIS authorization

### ISSUE THREAD

**Issue by warehousman** [edenlabllc/ehealth.api#214]
As NHS manager i want to ban MIS but not MSP.

- [x] Create [solution specification](https://edenlab.atlassian.net/wiki/x/KQCOAw) 
- [x] Implement
- [x] Deploy
- [x] Testing [Tests](https://edenlab.atlassian.net/wiki/x/IoFfBQ)

**Comment by lymychp** [comment]
@pzhuk please provide your inputs

**Comment by pzhuk** [comment]
So as result of our discussion

* separate MIS API-key has to be introduced
* API-key would be issued for new specific user-type in mithrill (i.e. MIS)
* each MIS would have list of allowed scopes as per mithril spec
* MIS API key authorization has to take precedence over all other user (i.e. MSP/client) authorization checks. For example: if MIS is unauthorized to register Declaration, but MSP is authorized, request has to be REJECTED, because MIS check has higher priority.
* we have to decide on a specific error message to be returned in case of unauthorized MIS. Message should be very specific, and not overlapping with any other messages in the system, i.e "403 Forbidden Client"

**Comment by EdwardVoloshin** [comment]
**problem 1.**
 if broker_scopes not found in JSON priv_settings with correct api-key: 
must be "if not found `broker_scopes` -  return 422 error  "Incorrect broker settings!"
now return 401 error "API-KEY header is invalid."
 `curl -X GET \
  https://dev.ehealth.world/api/drugs \
  -H 'api-key: f0c0d6d3696ca1b23811' \
  -H 'authorization: Bearer RjAraEZNVWNKaHliZlVta3J1S2VtQT09' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: fb5bdee2-e17f-289a-6db3-ea904e12690a'`

**Comment by EdwardVoloshin** [comment]
**problem 2.**
if not found needed broker scope + correct user_role scope:
must be 422 or other  (non 403!!!) " Scope is not allowed by broker !"
now return 403 - Your scope does not allow to access this resource. Missing allowances: drugs:read
`curl -X GET \
  https://dev.ehealth.world/api/drugs \
  -H 'api-key: 8c1b3126eb3be5909a6b' \
  -H 'authorization: Bearer RjAraEZNVWNKaHliZlVta3J1S2VtQT09' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: 909bee25-bfe0-0ae3-1a22-631d4fb4d39e'`

**Comment by PavelVesnin** [comment]
@EdwardVoloshin problem 1 solved

**Comment by EdwardVoloshin** [comment]
case 1 - test passed.

**Comment by PavelVesnin** [comment]
@EdwardVoloshin problem 2 solved

**Comment by EdwardVoloshin** [comment]
case 2 - test passed.
