### ISSUE TITLE
DB level encryption planning

### ISSUE THREAD

**Issue by warehousman** [edenlabllc/ehealth.api#226]
DB level encryption should be done.
Key management process should be designed and approved

**Comment by lymychp** [comment]
- [ ] ensure that enterprise Postgres is the only solution
- [ ] get prices
- [ ] approve with the PO

**Comment by AndrewDryga** [comment]
Actually, there are other options, for eg.: [Cassandra supports TDE](https://www.datastax.com/dev/blog/using-transparent-data-encryption-in-datastax-enterprise) in DataStax (paid) edition.

**Comment by AndrewDryga** [comment]
Basically, our job is to minimize security perimeter for sensitive data in our database. There are few steps that can be done in this direction:

1. Backups encryption (already done). Minimizes perimeter by removing backups storage from it.

2. Transparent Data Encryption on a database side (TDE). Some (Cassandra, MSSQL, Oracle, etc.) databases can encrypt all data that is stored on disk, reducing perimeter by removing cloud disk access from it.

Although, if you have access to the application you can query for unencrypted data. Also, if you were able to read encryption key along with the encrypted data - you can decrypt everything.

Arising problem - how to securely store and rotate encryption keys? More they live, less secure they are. And how to manage access to the database for its clients?

3. Application-level encryption / zero-knowledge DB.

Data can be encrypted on the application side and stored in a K/V storage. Reduces perimeter by removing access to the DB and all related parts altogether.

Key management is easier because tools like Vault/Coud's KMS can be leveraged to use encryption as a service.

Arising problem - complex queries over the data is not possible. Search algorithms/indexes should be done on the application side. The application itself is in a perimeter.

4. Client-level encryption.

If all platform consumers carry a private key that can be used for encryption, all sensitive data can be locked until client decrypts if for a specific data consumer.

Reference materials:
- https://security.stackexchange.com/questions/16939/is-it-generally-a-bad-idea-to-encrypt-database-fields
- https://gist.github.com/thiloplanz/e1136a04b26c138c8225

**Comment by lymychp** [comment]
Результаты изучения вариантов реализации TDE на Postgres
Поиск и исследования показали что ни Postgres ни  Postgres Plus не имеет встроенного TDE и рассматривается несколько других
вариантов шифрования, которые можно найти на странице с документацией postgresql
https://www.postgresql.org/docs/9.6/static/encryption-options.html

На данный момент
postgresql предлагает несколько вариантов шифрования данных.В частности, нас может интересовать всего несколько из них:
1.Data Partition Encryption
2.Encryption For Specific Columns

В первом варианте используется шифрование на уровне файловой системы или шифрование всего диска
на блочном уровне. Предлагается использвать linux утилиты, например eCryptfs,dm-crypt + LUKS и тд.

Данный вариант эффективен при физической краже диска, т.к. смонтировать его на другом копьютере, не имея ключей, невозможно.
Но в нашем случае диски по умолчанию шифруются посредством google cloud и в этом нет необходимости.
При смонтированном состоянии система видит все данные в незашифрованном виде.

Оставшийся вариант, это “Encryption For Specific Columns”. В данном случае используется модуль pgcrypto, он позволяет
шифровать данные избранных полей. Шифровать и расшифровывать данные можно “на лету” - конкретные колонки в
конкретных таблицах. Делать это нужно на уровне приложения (т.е. уровнем выше
самой базы). Но данный подход существенно повлияет на производительность системы. Кроме того, это потребует еще придумать механизм хранения ключей так, чтобы к ним не было доступа у админов кластера.
А также прийдется написать прослойку шифрования для всех приложений. И как результат - нельзя будет реализовать алгоритмы поиска и дедубликации.

Как итог - или менять БД или шифровать на лету, что имеет свои недостатки, опасно и трудоемко.
А с учетом того что данные у нас храняться GCS в шифрованном виде и доступны только админу кластера, то предлагается пока отложить реализацию. 

Материалы:
https://www.enterprisedb.com/blog/postgres-and-transparent-data-encryption-tde
https://www.postgresql.org/docs/9.6/static/encryption-options.html

**Comment by lymychp** [comment]
@AndrewDryga so what is the solution?

**Comment by AndrewDryga** [comment]
We had a meeting with Paul from the project office team and agreed on:
1. We don't really need TDE features while we are on cloud;
2. On planned migration to Ukrainian DC we would use FS encryption or the one that is provided by pgcrypto module;

Also, we are going to investigate pgcrypto to make sure it suits our needs in case we will increase priority for this issue.

**Comment by lymychp** [comment]
[Summary](https://docs.google.com/document/d/1W3AnTwox30I2B9ZidTyZ0Oy8twFPi-vGOFVuNW4UX3Y/edit)
