### ISSUE TITLE
Semi Block Chain

### ISSUE THREAD

**Issue by warehousman** [edenlabllc/ehealth.api#227]
@Peter please add description here

**Comment by lymychp** [comment]
- [ ] choose solution (tool)

**Comment by AndrewDryga** [comment]
We need to make sure that data in our DB can not be changed even by system super administrators, nowadays there is an existing solution for this task - blockchain. Full integration of blockchain principles requires us to de-centralize our database and come up with some proof algorithm (common ones are proof of work and proof of stake). 

Due to that DB carries sensitive data, which can not be disclosed, and unnecessary performance overhead for proofs - full blockchain usage is not possible. However, we can come up with very similar and centralized solution, which keeps both performance and data governance benefits:

1. Count each individual record as transaction;
2. Group transactions in blocks based on time threshold - produce a new block each N hours/days;
3. Sign transactions and the hash of the previous block with the personal private key of the user that generated transaction (similarly to a proof of stake).

Thus, data becomes unchangeable since it goes into the block `N-2` (where `N` - is the current block which continues to accept new transactions), with integrity reliability that grows over time. 
**To change data that is mined in a block, perpetrator needs to acquire all private keys of each single person that signed a transaction in never blocks. Or he needs to hack each single accredited key certification center that we support.**

**Possible implementation options:**
- PostgreSQL extension that is written in C with constraints enforcement on each single data insert;
- Custom Elixir application that fetches data from a database and enforces constraints on its side and a scheduled governance procedure that validates backward data integrity.

**Does it scale?**
Our data is not tightly coupled, so it can be simply sharded over multiple database instances, however:
- During block generation, we need the access to all transactions and a complete TX history (for backward integrity check).
- During TX insert we need access to immutable counter

**Can we make it highly available?**

**Implementation tradeoffs:**
- Immutability vs partial immutability of a data. We may prefer to keep some fields out of hashing so that we can change declaration status without growing our data set. **Data storages are cheap nowadays and immutability would provide better introspection.**

**Do not:**
- Persist row hashes elsewhere and reuse them for merkle trees. This would require us to build an additional integrity check to make sure that data is not changed independently from this hashes.

**Open questions**
- What is the right procedue for detected failed integrity checks? Possible option: restore corrupted block from a backup and re-run integrity check, after that cancel everything since last valid transaction.
- What to do with new-coming transactions that link to the `N-2` block? Possible option: decline them and require a user to send a new TX with a link to the `N-1` block.
