### ISSUE TITLE
Declaration limit calculation v.3

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#3345]
As  NHS, I want eHealth to automatically monitor the number of active doctor's declarations and not allow to create a declaration over the limit, in order to ensure proper quality of medical services provided by the doctor.

Validate Declaration limit according to [spec](https://edenlab.atlassian.net/wiki/spaces/EH/pages/983335/IL.Create+declaration+request#IL.Createdeclarationrequest-Validatedeclarationlimit)

**Comment by IrinaRevutska** [comment]
As  NHS, I want eHealth to automatically monitor the number of active doctor's declarations and not allow to create a declaration over the limit, in order to ensure proper quality of medical services provided by the doctor.

Validate Declaration limit on create declaration:
1. Count all declarations in status `active` where OPS.declarations.employee_id==$.declaration_request.employee_id
1.1 If there is an active declaration with the current person, exclude it from the selection
2. Count all declaration_requests in status approved where IL.declaration_requests.data($.employee.id) ==$.declaration_request.employee_id
3. Select config parameter for declarations_limit where speciality == $.declaration_request.scope
4. Compare the result of selections with config parameter. In case count declarations+declaration_requests > config_parameter, return 409 "The employee has reached the declaration limit"
