### ISSUE TITLE
duplicated persons after deduplication

### ISSUE THREAD

**Issue by svetavedmed** [edenlabllc/ehealth.api#4474]
after deduplication process there are duplicated persons in DB
there are examples of such persons in all environment.
ex from prod - [-.txt](https://zube.io/files/edenlabllc/38f05fb831bb2909db9d28d0ba1d7e7a--.txt)

**Comment by PavelVesnin** [comment]
migration for index creation is already [exists](https://github.com/edenlabllc/mpi.api/blob/develop/apps/core/priv/repo/migrations/20190207180500_mc_uniq_index.exs#L7)
But creation was failed because of concurrently index creation (duplicated candidates was already in DB before index).
```
"merge_candidates_master_person_person_index" UNIQUE, btree (master_person_id, person_id) INVALID
```
So this problem should fixed manually:
- find and drop duplicated rows
- create index repeatedly
