### ISSUE TITLE
Declaration request - Signed URLs generation.

### ISSUE THREAD

**Issue by lymychp** [edenlabllc/ehealth.api#785]
As a MIS
I want to be able to load the scanned documents directly from the client's browser, not through my BE.
So that I can significantly decrease the load on my servers and will help to save the planet.

Currently pre-generated signed urls cannot be used because there is no CORS in the link. [Google documentation regarding cors](https://cloud.google.com/storage/docs/access-control/signed-urls)

It is suggested to add `origin` parameter to the `client.settings` in Mithril. 
Another option - use redirect_uri.
And use this `origin` during the signed url generation.

**Comment by gmile** [comment]
Let's go with adding a new setting to the `settings` field on `clients` table. A `redirect_url` may not necessarily represent include the origin, from which the client's UI works.

**Comment by gmile** [comment]
@lymychp here's the current plan as I see it:

1. require all future MISs to provide a domain name to be used as `cors_origin`, e.g. a name under which their UI works,
2. ask all current MISs (or at least those in need) to provider `cors_origin`,
3. during `declaration_request` creation, grab `cors_origin` using the following "path":

    ```
    current_user -> current_msp_client -> mis_registrar -> mis_client -> settings -> cors_origin
    ```
4. for each offline document type in `declaration_request`:

  * make a GET signed URI, making sure **CORS info is present** in the signed URI

**Comment by gmile** [comment]
@lymychp before starting this, I'll wait until you sign off on the above.

**Comment by lymychp** [comment]
4. We should create `PUT` URL, not `GET`

**Comment by gmile** [comment]
Turns out it is not possible to add CORS per signed_url. From the [docs](https://cloud.google.com/storage/docs/cross-origin):

> Cloud Storage allows you to set CORS configuration at the bucket level only.

We will do the following:

* ask all MISs about their origin,
* configure all origins in all 3 buckets: declaration-requests-dev (dev/demo), **declaration-requests-preprod** (preprod) and **declaration-requests** (prod),
* update MIS setup instructions to include a step to amend bucket CORS info in all environments.

So far I've done the following:

* configured CORS info for our first MIS on **declaration-requests-dev**, **declaration-requests-preprod** and **declaration-requests** buckets.

In order to verify that CORS info is indeed working for each bucket, do this:

```
curl -I -H "Origin: URL_OF_OUR_FIRST_MIS" https://storage.googleapis.com/declaration-requests-dev/
curl -I -H "Origin: URL_OF_OUR_FIRST_MIS" https://storage.googleapis.com/declaration-requests-preprod/
curl -I -H "Origin: URL_OF_OUR_FIRST_MIS" https://storage.googleapis.com/declaration-requests/
```

In response two headers will be seen: `Access-Control-Allow-Origin` and `Access-Control-Expose-Headers`.

In order to verify that CORS info is not working for anyone else:
```
curl -I -H "Origin: http://something.com" https://storage.googleapis.com/declaration-requests-dev/
curl -I -H "Origin: http://something.com" https://storage.googleapis.com/declaration-requests-preprod/
curl -I -H "Origin: http://something.com" https://storage.googleapis.com/declaration-requests/
```

**Comment by gmile** [comment]
@lymychp let's please test this, and close the issue. For gathering/registering origins from other MISs, as well as to create/update "MIS registration memo" (as discussed on slack) we should open separate small chore tasks.

**Comment by lymychp** [comment]
I have asked Helsi to test it. Waiting for response.

**Comment by lymychp** [comment]
@gmile отримали відповідь 
>Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. Origin 'http://dis.helsi.dev' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute

**Comment by gmile** [comment]
Being done in:

* https://github.com/edenlabllc/ehealth.api/pull/927
* https://github.com/edenlabllc/ael.api/pull/2

**Comment by gmile** [comment]
@lymychp @AlekzandrV in order to test this do two things:

1. generate secure URL,
2. try to upload something to that secure URL.

Here's how to do that:

1. generate secure URL:

    ```bash
    $ gsutil signurl -c "image/jpeg" -m PUT -d 1d priv/service_account_key.json gs://declaration-requests-dev/testing/sample_file.jpeg
    ```

    This must be run from a folder, where `priv/service_account_key.json` exists. For instance, from `ael.api` app's folder. Ask @PavelVesnin for more info about `priv/service_account_key.json`.

    After a link is generated, copy it to buffer.

2. upload something to that secure URL:

    Open the following URLs in Chrome:

    ```
    https://helsi.me
    ```

    All origins, available at the time of writing this:

    * https://helsi.me
    * http://dis.helsi.dev
    * https://stagingreform.helsi.me

    Run the following JavaScript code in Chrome Developer Tools console:

    ```javascript
    function reqListener() {  
      console.log(this.responseText);  
    }

    function reqError(err) {  
      console.log('Fetch Error :-S', err);  
    }

    var oReq = new XMLHttpRequest();  
    oReq.onload = reqListener;  
    oReq.onerror = reqError;  
    oReq.open('put', 'SECURE_URL', true);
    oReq.setRequestHeader("Content-Type", "image/jpeg");
    oReq.send("sometextordata1234");
    ```

    Make sure to replace SECURE_URL with a value, copied to buffer during previous step.

After the JavaScript code is ran, no warnings or errors should be present in Developer Tools console – this is indication that the process completed successfully. To double-check, make sure to find uploaded file on Google Storage's bucket:

```
$ gsutil cat gs://declaration-requests-dev/testing/sample_file.jpeg
sometextordata1234
```

**Comment by lymychp** [comment]
deployed to demo and preprod
